### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by 59471032** [dromara/soul-dashboard#1]
Failed to compile.

./node_modules/history/esm/history.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in '/Users/baocj/Downloads/soul-dashboard-master/node_modules/history/esm'

**Comment by ZuileGuangyin** [comment]
解决方案 将 roadhog 版本修改为  "^2.5.0-beta.4"

修改后npm更新开发环境依赖包

npm update roadhog --save-dev
