### ISSUE TITLE
版本不一致

### ISSUE THREAD

**Issue by chengzi520** [dromara/soul-dashboard#4]
为什么和官网压缩后的前后端长的不一样啊，有官网压缩前的么？？？

**Comment by yu199195** [comment]
官网压缩的，在soul-admin下面

**Comment by chengzi520** [comment]
想要图二版本的前端页面，有么？？？
------------------ 原始邮件 ------------------
发件人: "流浪诗人"<notifications@github.com>;
发送时间: 2019年10月16日(星期三) 晚上6:28
收件人: "Dromara/soul-dashboard"<soul-dashboard@noreply.github.com>;
抄送: "李慧琴"<1479069210@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Dromara/soul-dashboard] 版本不一致 (#4)




官网压缩的，在soul-admin下面

**Comment by yu199195** [comment]
这个不就是吗
