### ISSUE TITLE
前端代码是不是还没有元数据管理部分

### ISSUE THREAD

**Issue by imwolf** [dromara/soul-dashboard#5]
1.  这是dashboard npm start的界面，相比soul-admin中的界面缺少元数据管理部分
![image](https://user-images.githubusercontent.com/1636210/75771002-09d14f80-5d84-11ea-88bc-55fe39f27bc7.png)
2. 这是soul-admin中的用户界面
![image](https://user-images.githubusercontent.com/1636210/75771092-36856700-5d84-11ea-9f46-8daa142de213.png)
 
尝试在源代码中搜索"元数据管理"也没有找到，请问是这部分没有放出来还是我的操作方式不对呀~

**Comment by yu199195** [comment]
在其他的分支
