### ISSUE TITLE
怎么访问后台服务呢？

### ISSUE THREAD

**Issue by byla678** [dromara/soul-dashboard#6]
你好，我是个纯前端，按照文档已经npm start,输入账号密码后没反应，请问是需要启动什么后台服务或者mock数据吗？

**Comment by yu199195** [comment]
这里只是前段的源码，后端需要启动 soul-admin ，
你可以参考这里 ：https://dromara.org/zh-cn/docs/soul/admin.html
本地需要有jdk8+  和mysql 数据库
