### ISSUE TITLE
[bug]Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by UsherChen** [dromara/soul-dashboard#78]
Hi!
I followed the build steps to build this project, but there was an error at the start. 
The code is cloned directly from git without any changes.
![image](https://user-images.githubusercontent.com/1931327/109128050-0c456a00-778a-11eb-8a70-dbeaf5dbcbdc.png)

It says : Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

**Comment by dengliming** [comment]
Can you explain the environment you use? e.g.  node version.

**Comment by UsherChen** [comment]
> Can you explain the environment you use? e.g. node version.
We have this problem on both Mac10.12、Mac10.15 and Ubuntu 16.04。
Node version：v14.15.4

**Comment by dengliming** [comment]
resolved by

**Comment by fengzhenbing** [comment]
@ant-design/icons 's version conflict. I will fix it.
