### ISSUE TITLE
Remove unused Hystrix folder

### ISSUE THREAD

**Issue by dengliming** [dromara/soul-dashboard#93]
Currently, we already used common page for all plugin.

**Comment by himanshu007-creator** [comment]
i would like to work on this issue.

**Comment by yu199195** [comment]
hystrix can  used common ？

**Comment by himanshu007-creator** [comment]
i thought issue was about deleting hysterix folder

**Comment by yu199195** [comment]
We need to confirm the function first ，If there's no problem， you can do it @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> We need to confirm the function first ，If there's no problem， you can do it @himanshu007-creator

Okay sure, whenever it's decided, let me know

**Comment by dengliming** [comment]
@himanshu007-creator Sorry for my mistake. We can't remove this folder for now. Thanks. You are welcome to try other issues : )

**Comment by himanshu007-creator** [comment]
okay👍🏽
