### ISSUE TITLE
Make ParamsType field not required when editing metadata

### ISSUE THREAD

**Issue by dengliming** [dromara/soul-dashboard#97]
![image](https://user-images.githubusercontent.com/7796156/115985835-41323980-a5e0-11eb-8181-369ea86a7175.png)

**Comment by qurenneng** [comment]
1

**Comment by dengliming** [comment]
Resolved by [https://github.com/dromara/soul-dashboard/pull/98](https://github.com/dromara/soul-dashboard/pull/98)
