### ISSUE TITLE
Adjust window size to adapt strategy names

### ISSUE THREAD

**Issue by tuohai666** [dromara/soul-dashboard#99]
Adjust window size to adapt strategy names of Groovy, TimeBefore and TimeAfter.

Selectors:
![image](https://user-images.githubusercontent.com/24643893/116035369-78afed00-a697-11eb-99cd-ee38605986d4.png)

Rules:
![image](https://user-images.githubusercontent.com/24643893/116035414-882f3600-a697-11eb-98c2-6e42f37f8f51.png)

**Comment by orangeyts** [comment]
I take
